#!/usr/bin/env python3
"""
Star/nation/route/world canon values — AUTO-GENERATED from the live DB
2026-07-04 (post-Master-Timeline, post-cleanup).

Sections:
  CLEANUP_SQL        — junk-host exoplanet rows + exact duplicates (idempotent)
  FULL_STARS         — complete rows for stars absent from JSON/CSV sources
  STARS/NATIONS/...  — canon column values once applied only to the live DB
  FICTIONAL_WORLDS   — the AUTHORITATIVE full fictional_exoplanets table
                       (replace-style: rows here define the table)

Chain position: AFTER migrate_to_sqlite.py, BEFORE migrate_timeline_events.py.
Regenerate from a live DB whenever planetary/star/nation canon moves.
"""

import os
import sqlite3

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "starmap.sqlite")

CLEANUP_SQL = [
    "DELETE FROM exoplanets WHERE host_star_name LIKE 'Star %'",
    "DELETE FROM exoplanets WHERE id NOT IN "
    "(SELECT MIN(id) FROM exoplanets GROUP BY name, host_star_name)",
    "DELETE FROM fictional_exoplanets WHERE id NOT IN "
    "(SELECT MIN(id) FROM fictional_exoplanets GROUP BY name, host_star_name)",
]

FULL_STAR_COLUMNS = ['id', 'hip', 'hd', 'bayer', 'flamsteed', 'constellation', 'proper_name', 'fictional_name', 'fictional_description', 'x', 'y', 'z', 'dist', 'ra', 'dec', 'magnitude', 'absolute_magnitude', 'spectral_class', 'color_index', 'luminosity', 'nation_id', 'is_fictional', 'era_start', 'era_end', 'discovery_number', 'discovery_year']

FULL_STARS = [{'absolute_magnitude': 13.1,
  'bayer': None,
  'color_index': 2.0,
  'constellation': 'LMi',
  'dec': 31.966,
  'discovery_number': None,
  'discovery_year': None,
  'dist': 14.93,
  'era_end': None,
  'era_start': None,
  'fictional_description': 'The shadow-sun: 20 Leonis Minoris B, the M7V red dwarf companion of '
                           'Holstensonne. A symbol of companionship in Union lore.',
  'fictional_name': 'Shattensonne',
  'flamsteed': None,
  'hd': None,
  'hip': None,
  'id': 999997,
  'is_fictional': 1,
  'luminosity': 0.0005,
  'magnitude': 14.0,
  'nation_id': None,
  'proper_name': '20 LMi B',
  'ra': 10.031,
  'spectral_class': 'M7V',
  'x': -11.038308,
  'y': 6.336788,
  'z': 7.956742},
 {'absolute_magnitude': 11.6,
  'bayer': None,
  'color_index': 1.53,
  'constellation': 'Vol',
  'dec': -68.31305555555555,
  'discovery_number': 11,
  'discovery_year': 2225,
  'dist': 10.6,
  'era_end': 3000,
  'era_start': 2170,
  'fictional_description': 'Terran-controlled frontier system (M3V) 10.6 pc from Sol. Site of the '
                           'loss of ISN Bismarck and T. Roosevelt. Home to Foxtrot (L 98-59 f), '
                           'the outermost known world.',
  'fictional_name': 'L 98-59',
  'flamsteed': None,
  'hd': None,
  'hip': None,
  'id': 999998,
  'is_fictional': 1,
  'luminosity': 0.002,
  'magnitude': 11.7,
  'nation_id': 'terran_directorate',
  'proper_name': 'L 98-59',
  'ra': 8.3016,
  'spectral_class': 'M3Ve',
  'x': -2.21999157743081,
  'y': 3.227241140366877,
  'z': -9.849698067355149},
 {'absolute_magnitude': 4.7,
  'bayer': None,
  'color_index': 0.68,
  'constellation': 'LMi',
  'dec': 34.2,
  'discovery_number': None,
  'discovery_year': 2220,
  'dist': 16.86,
  'era_end': 3000,
  'era_start': 2170,
  'fictional_description': 'Tiefe-Grenze Tor (HD 86729) — Union frontier colony system 16.86 pc '
                           'from Sol. Colony world Brandstadt (c) is transitioning from outpost to '
                           'full colonial world.',
  'fictional_name': 'Tiefe-Grenze Tor',
  'flamsteed': None,
  'hd': 86729.0,
  'hip': None,
  'id': 999999,
  'is_fictional': 1,
  'luminosity': 0.9,
  'magnitude': 9.5,
  'nation_id': None,
  'proper_name': 'HD 86729',
  'ra': 10.017,
  'spectral_class': 'G5V',
  'x': -12.799522,
  'y': 7.022058,
  'z': 8.42886}]

STARS = [{'id': 3814,
  'fictional_name': 'Eta Cassiopeiae',
  'fictional_description': 'Fictional name from the Felgenland universe',
  'nation_id': '',
  'discovery_number': None,
  'discovery_year': None,
  'era_start': None,
  'era_end': None},
 {'id': 8087,
  'fictional_name': 'Tau Ceti',
  'fictional_description': 'Terran Directorate-controlled system 3.65 pc from Sol. Home to the '
                           'colony worlds Asimov (habitable), Heinlein, Poul, and Bester — all '
                           'named for classic SF authors.',
  'nation_id': 'terran_directorate',
  'discovery_number': 6,
  'discovery_year': 2192,
  'era_start': None,
  'era_end': None},
 {'id': 16496,
  'fictional_name': 'Epsilon Eridani',
  'fictional_description': 'ε Eridani (Ran) — noted as a Rimstar in Felgenland Saga lore. 3.22 pc '
                           'from Sol.',
  'nation_id': 'terran_directorate',
  'discovery_number': 4,
  'discovery_year': 2191,
  'era_start': None,
  'era_end': None},
 {'id': 37173,
  'fictional_name': '',
  'fictional_description': 'Procyon (α CMi) — client state of the Terran Directorate. 3.51 pc from '
                           'Sol.',
  'nation_id': 'terran_directorate',
  'discovery_number': 5,
  'discovery_year': 2191,
  'era_start': None,
  'era_end': None},
 {'id': 43464,
  'fictional_name': 'Griefen Tor',
  'fictional_description': 'Greifen Tor is the gateway to Felgenland Union rimward space, a '
                           'bustling trade hub orbiting the system known to Earth astronomers as '
                           '55 Cancri.',
  'nation_id': 'felgenland_union',
  'discovery_number': 12,
  'discovery_year': 2230,
  'era_start': None,
  'era_end': None},
 {'id': 46945,
  'fictional_name': 'Brandenburg Tor',
  'fictional_description': 'Brandenburg Tor (11 LMi) — Union Industrial Heartland System 11.37 pc '
                           'from Sol. Major manufacturing and logistics hub; capital world: '
                           'Hansaburgh.',
  'nation_id': 'felgenland_union',
  'discovery_number': 7,
  'discovery_year': 2200,
  'era_start': None,
  'era_end': None},
 {'id': 47977,
  'fictional_name': 'Helvetia Tor',
  'fictional_description': 'G2V solar twin designated Helvetia Tor at the 2371 chartering of Neu '
                           'Helvetica — a Cultural Renaissance peace colony in the Leo Minor home '
                           'cluster, 17.3 light-years from Holsten Tor.',
  'nation_id': '',
  'discovery_number': None,
  'discovery_year': 2371,
  'era_start': None,
  'era_end': None},
 {'id': 48941,
  'fictional_name': 'Holsten Tor',
  'fictional_description': 'Holsten Tor (20 LMi) — Union Core Capital System 15.05 pc from Sol. '
                           'Capital world: Stahlburgh. Home of the Felgenland Union government.',
  'nation_id': 'felgenland_union',
  'discovery_number': 9,
  'discovery_year': 2215,
  'era_start': None,
  'era_end': None},
 {'id': 49558,
  'fictional_name': 'Pathfinder Tor',
  'fictional_description': "The Explorer Corps' first great prize: a long-lived K0 dwarf with a "
                           'near-Earth world in its habitable zone, opened for settlement by the '
                           'Pathfinder Teams and named in their honor.',
  'nation_id': '',
  'discovery_number': None,
  'discovery_year': 2380,
  'era_start': None,
  'era_end': None},
 {'id': 49767,
  'fictional_name': 'Pentothia Prime',
  'fictional_description': '',
  'nation_id': 'neutral_zone',
  'discovery_number': None,
  'discovery_year': None,
  'era_start': None,
  'era_end': None},
 {'id': 53879,
  'fictional_name': 'Lalande 21185',
  'fictional_description': 'Contested border system 2.55 pc from Sol. Libertad (b) was the first '
                           'human colony outside Sol; Nakdong (c) became a bitter war-zone — site '
                           "of Max's long patrol.",
  'nation_id': 'terran_directorate',
  'discovery_number': 1,
  'discovery_year': 2170,
  'era_start': None,
  'era_end': None},
 {'id': 55681,
  'fictional_name': 'Argylle Tor',
  'fictional_description': "K0V orange dwarf named in 2356 for Alasdair Campbell's province of "
                           'Argyll-Inveraray-on-the-Greenwich — a frontier gateway star and home '
                           'of the Heatherly colony.',
  'nation_id': 'felgenland_union',
  'discovery_number': 13,
  'discovery_year': 2356,
  'era_start': None,
  'era_end': None},
 {'id': 56828,
  'fictional_name': 'Protelan',
  'fictional_description': 'Protelan system (61 UMa) 9.61 pc from Sol — core Union world. Capital: '
                           'Protelan, a moon of the gas giant Grandpere. Seat of the Protelani '
                           'Republic.',
  'nation_id': 'protelani_republic',
  'discovery_number': 8,
  'discovery_year': 2184,
  'era_start': None,
  'era_end': None},
 {'id': 70666,
  'fictional_name': '',
  'fictional_description': '',
  'nation_id': '',
  'discovery_number': None,
  'discovery_year': 2184,
  'era_start': None,
  'era_end': None},
 {'id': 71453,
  'fictional_name': '',
  'fictional_description': 'Alpha Centauri B — secondary star of the Hawking system. 1.32 pc from '
                           'Sol.',
  'nation_id': '',
  'discovery_number': None,
  'discovery_year': 2184,
  'era_start': None,
  'era_end': None},
 {'id': 71456,
  'fictional_name': 'Hawking',
  'fictional_description': 'Alpha Centauri A — the settler name for the whole Alpha Centauri '
                           'system is Hawking. The Terran Directorate designates its primary '
                           'habitable world Hawking Prime (α Cen A c). 1.32 pc from Sol.',
  'nation_id': '',
  'discovery_number': 2,
  'discovery_year': 2184,
  'era_start': None,
  'era_end': None},
 {'id': 98924,
  'fictional_name': 'Delta Pavonis',
  'fictional_description': 'Fictional name from the Felgenland universe',
  'nation_id': '',
  'discovery_number': None,
  'discovery_year': None,
  'era_start': None,
  'era_end': None},
 {'id': 101479,
  'fictional_name': 'HD 10180',
  'fictional_description': 'Fictional name from the Felgenland universe',
  'nation_id': '',
  'discovery_number': None,
  'discovery_year': None,
  'era_start': None,
  'era_end': None},
 {'id': 113008,
  'fictional_name': '',
  'fictional_description': 'Independent republic capital system (α PsA) 7.7 pc from Sol. Capital '
                           'world: Valorgraemo (α PsA c), seat of the Fomalhaut Republic.',
  'nation_id': 'dorsai_republic',
  'discovery_number': 10,
  'discovery_year': 2220,
  'era_start': None,
  'era_end': None},
 {'id': 118720,
  'fictional_name': '',
  'fictional_description': 'Wolf 359 — site of a notable military operation in the Felgenland '
                           'Saga. 2.39 pc from Sol.',
  'nation_id': '',
  'discovery_number': 3,
  'discovery_year': 2188,
  'era_start': None,
  'era_end': None},
 {'id': 500000,
  'fictional_name': '',
  'fictional_description': '',
  'nation_id': '',
  'discovery_number': 0,
  'discovery_year': None,
  'era_start': None,
  'era_end': None},
 {'id': 999997,
  'fictional_name': 'Shattensonne',
  'fictional_description': 'The shadow-sun: 20 Leonis Minoris B, the M7V red dwarf companion of '
                           'Holstensonne. A symbol of companionship in Union lore.',
  'nation_id': None,
  'discovery_number': None,
  'discovery_year': None,
  'era_start': None,
  'era_end': None},
 {'id': 999998,
  'fictional_name': 'L 98-59',
  'fictional_description': 'Terran-controlled frontier system (M3V) 10.6 pc from Sol. Site of the '
                           'loss of ISN Bismarck and T. Roosevelt. Home to Foxtrot (L 98-59 f), '
                           'the outermost known world.',
  'nation_id': 'terran_directorate',
  'discovery_number': 11,
  'discovery_year': 2225,
  'era_start': 2170,
  'era_end': 3000},
 {'id': 999999,
  'fictional_name': 'Tiefe-Grenze Tor',
  'fictional_description': 'Tiefe-Grenze Tor (HD 86729) — Union frontier colony system 16.86 pc '
                           'from Sol. Colony world Brandstadt (c) is transitioning from outpost to '
                           'full colonial world.',
  'nation_id': None,
  'discovery_number': None,
  'discovery_year': 2220,
  'era_start': 2170,
  'era_end': 3000}]

NATIONS = [{'id': 'dorsai_republic', 'era_start': 2210, 'era_end': 3000},
 {'id': 'felgenland_union', 'era_start': 2267, 'era_end': 3000},
 {'id': 'lalande_republic', 'era_start': 2353, 'era_end': 3000},
 {'id': 'neutral_zone', 'era_start': 2170, 'era_end': 3000},
 {'id': 'protelani_republic', 'era_start': 2184, 'era_end': 2390},
 {'id': 'terran_directorate', 'era_start': 2091, 'era_end': 3000}]

TRADE_ROUTES = [{'id': 'centauri_sirius_trade_route_6', 'era_start': 2091, 'era_end': 3000},
 {'id': 'dorsai_brandenburg_trade_route_18', 'era_start': 2210, 'era_end': 3000},
 {'id': 'dorsai_felgenland_military_alliance_route_14', 'era_start': 2210, 'era_end': 3000},
 {'id': 'dorsai_griefen_trade_route_19', 'era_start': 2210, 'era_end': 3000},
 {'id': 'dorsai_lalande_colony_trade_route_17', 'era_start': 2210, 'era_end': 3000},
 {'id': 'dorsai_protelan_defense_corridor_15', 'era_start': 2210, 'era_end': 3000},
 {'id': 'holsten_brandenburg_route_8', 'era_start': 2267, 'era_end': 3000},
 {'id': 'pentothian_dorsai_trade_22', 'era_start': 2170, 'era_end': 3000},
 {'id': 'pentothian_felgenland_trade_21', 'era_start': 2170, 'era_end': 3000},
 {'id': 'pentothian_protelan_trade_23', 'era_start': 2170, 'era_end': 3000},
 {'id': 'pentothian_terran_neutral_trade_20', 'era_start': 2170, 'era_end': 3000},
 {'id': 'protelan_brandenburg_express_11', 'era_start': 2199, 'era_end': 3000},
 {'id': 'protelan_holsten_commercial_corridor_10', 'era_start': 2199, 'era_end': 3000},
 {'id': 'protelan_trade_corridor_13', 'era_start': 2199, 'era_end': 3000},
 {'id': 'sirius_proxima_trade_link_5', 'era_start': 2091, 'era_end': 3000},
 {'id': 'tiefe_grenze_brandenburg_frontier_route_25', 'era_start': 2267, 'era_end': 3000},
 {'id': 'tiefe_grenze_griefen_frontier_route_26', 'era_start': 2267, 'era_end': 3000},
 {'id': 'tiefe_grenze_holsten_frontier_route_24', 'era_start': 2267, 'era_end': 3000}]

EXOPLANET_FICTIONAL_FLAGS = [{'equilibrium_temp_k': 255.0,
  'host_star_name': 'HD 99492',
  'name': 'Heatherly',
  'orbital_period_days': 298.0,
  'planet_mass_earth': 1.9,
  'planet_radius_earth': 1.3,
  'planet_type': 'Rocky',
  'potentially_habitable': 1,
  'semi_major_axis_au': 0.88,
  'star_id': 55681},
 {'equilibrium_temp_k': 280.0,
  'host_star_name': 'Fomalhaut',
  'name': 'Valorgraemo',
  'orbital_period_days': 2337.0,
  'planet_mass_earth': 2.8,
  'planet_radius_earth': 1.5,
  'planet_type': 'Rocky',
  'potentially_habitable': 1,
  'semi_major_axis_au': 4.3,
  'star_id': 113008}]

FICTIONAL_WORLD_COLUMNS = ['name', 'host_star_name', 'planet_type', 'description', 'orbit', 'period', 'mass', 'radius', 'parent_planet', 'map_url']

FICTIONAL_WORLDS = [{'description': 'Tidally locked super-Mercury nicknamed "Scorch" — dayside over 800 K, rich in '
                 'refractory metals. Surveyed but not colonized.',
  'host_star_name': 'Argylle Tor',
  'map_url': None,
  'mass': None,
  'name': 'Argylle I',
  'orbit': 0.08,
  'parent_planet': None,
  'period': 12.0,
  'planet_type': 'Hot Rocky',
  'radius': 1.2},
 {'description': 'Barren, airless world nicknamed "Cinder" — ancient lava flows, used as a '
                 'low-gravity training range for Assault drop operations.',
  'host_star_name': 'Argylle Tor',
  'map_url': None,
  'mass': None,
  'name': 'Argylle II',
  'orbit': 0.35,
  'parent_planet': None,
  'period': 100.0,
  'planet_type': 'Rocky',
  'radius': 0.6},
 {'description': 'Icy super-Earth nicknamed "Shield" — nitrogen-methane atmosphere, cryovolcanism, '
                 'a forward listening post over a subsurface ocean.',
  'host_star_name': 'Argylle Tor',
  'map_url': None,
  'mass': None,
  'name': 'Argylle IV',
  'orbit': 2.5,
  'parent_planet': None,
  'period': 1600.0,
  'planet_type': 'Ice Giant',
  'radius': 2.0},
 {'description': 'Ringed gas giant nicknamed "Guardian" — helium-3 and deuterium mining platforms '
                 'shelter in its magnetic field beside a naval refueling station.',
  'host_star_name': 'Argylle Tor',
  'map_url': None,
  'mass': None,
  'name': 'Argylle V',
  'orbit': 6.0,
  'parent_planet': None,
  'period': 6000.0,
  'planet_type': 'Gas Giant',
  'radius': 11.0},
 {'description': 'Neptune-like iceworld mined for water and methane volatiles.',
  'host_star_name': 'Brandenburg Tor',
  'map_url': None,
  'mass': 2.0,
  'name': 'Frostmeer',
  'orbit': 7.0,
  'parent_planet': None,
  'period': 6752.0,
  'planet_type': 'Ice Giant',
  'radius': 1.5},
 {'description': 'Temperate world of salt flats and farmland — capital of the Imperial Federation '
                 'of Hansaburgh and birthplace of Karl von Machthaber. Kaiserstadt hosts the '
                 "Congressional Building; Starveil Festivals mark Wogenstern's eclipses.",
  'host_star_name': 'Brandenburg Tor',
  'map_url': None,
  'mass': 1.1,
  'name': 'Hansaburgh',
  'orbit': 0.85,
  'parent_planet': None,
  'period': 360.0,
  'planet_type': 'Earth-like',
  'radius': 1.0},
 {'description': "Hot, Mercury-like world mined for metals and salts that feed Hansaburgh's "
                 'economy.',
  'host_star_name': 'Brandenburg Tor',
  'map_url': None,
  'mass': 0.4,
  'name': 'Salzkern',
  'orbit': 0.3,
  'parent_planet': None,
  'period': 80.0,
  'planet_type': 'Hot Rocky',
  'radius': 0.8},
 {'description': 'Jupiter-like giant whose icy moons host fuel depots for the Union trade lanes.',
  'host_star_name': 'Brandenburg Tor',
  'map_url': None,
  'mass': None,
  'name': 'Wogenstern',
  'orbit': 2.0,
  'parent_planet': None,
  'period': 1022.0,
  'planet_type': 'Gas Giant',
  'radius': 9.0},
 {'description': 'Rugged cool-temperate world (α PsA d) of rolling plains and coniferous forests — '
                 'training ground of the Fomalhaut shock troops, and an agricultural exporter.',
  'host_star_name': 'Fomalhaut',
  'map_url': None,
  'mass': 1.5,
  'name': 'Batalklendo',
  'orbit': 4.7,
  'parent_planet': None,
  'period': 2702.0,
  'planet_type': 'Earth-like',
  'radius': 1.1},
 {'description': 'Distant super-Jupiter (α PsA b) whose icy moons feed resource extraction — and '
                 "whose orbital defense platforms are the Republic's rimward bulwark.",
  'host_star_name': 'Fomalhaut',
  'map_url': None,
  'mass': None,
  'name': 'Fomalhaut b',
  'orbit': 177.0,
  'parent_planet': None,
  'period': 620500.0,
  'planet_type': 'Gas Giant',
  'radius': 11.0},
 {'description': 'Storm-wracked ocean world (α PsA e), 70% sea — naval bases and trade ports vital '
                 "to the Republic's maritime defense and rimward commerce.",
  'host_star_name': 'Fomalhaut',
  'map_url': None,
  'mass': 1.3,
  'name': 'Marrikoviro',
  'orbit': 5.2,
  'parent_planet': None,
  'period': 3141.0,
  'planet_type': 'Earth-like',
  'radius': 1.0},
 {'description': 'Super-Earth lava world (55 Cancri e) mined for rare minerals.',
  'host_star_name': 'Griefen Tor',
  'map_url': None,
  'mass': 8.0,
  'name': 'Eisfluss',
  'orbit': 0.01544,
  'parent_planet': None,
  'period': 0.74,
  'planet_type': 'Hot Rocky',
  'radius': 1.9},
 {'description': 'Cool gas dwarf (55 Cancri f) with icy moons mined for volatiles.',
  'host_star_name': 'Griefen Tor',
  'map_url': None,
  'mass': None,
  'name': 'Frostmeer',
  'orbit': 0.781,
  'parent_planet': None,
  'period': 260.0,
  'planet_type': 'Ice Giant',
  'radius': 7.0},
 {'description': 'Warm gas dwarf (55 Cancri c) yielding volatiles and silicates.',
  'host_star_name': 'Griefen Tor',
  'map_url': None,
  'mass': None,
  'name': 'Kernfluss',
  'orbit': 0.2403,
  'parent_planet': None,
  'period': 44.4,
  'planet_type': 'Gas Giant',
  'radius': 8.0},
 {'description': "Habitable ocean world of archipelagos — the Union's petroleum and helium-3 hub. "
                 "Capital: Strasseburgh. Sturmmeer's rare eclipses are celebrated as Tideveil "
                 'Festivals.',
  'host_star_name': 'Griefen Tor',
  'map_url': None,
  'mass': 1.2,
  'name': 'Lochiel',
  'orbit': 0.9,
  'parent_planet': None,
  'period': 320.0,
  'planet_type': 'Earth-like',
  'radius': 1.05},
 {'description': 'Jupiter-like giant (55 Cancri d) whose icy moons serve as Navy fuel depots.',
  'host_star_name': 'Griefen Tor',
  'map_url': None,
  'mass': None,
  'name': 'Sturmmeer',
  'orbit': 5.74,
  'parent_planet': None,
  'period': 5218.0,
  'planet_type': 'Gas Giant',
  'radius': 12.0},
 {'description': 'Warm gas giant (55 Cancri b) harvested for atmospheric gases and metals.',
  'host_star_name': 'Griefen Tor',
  'map_url': None,
  'mass': None,
  'name': 'Wolkenmeer',
  'orbit': 0.1134,
  'parent_planet': None,
  'period': 14.65,
  'planet_type': 'Gas Giant',
  'radius': 13.0},
 {'description': 'Jupiter-like giant whose moons host mining outposts of 5–10 million.',
  'host_star_name': 'Hawking',
  'map_url': None,
  'mass': None,
  'name': 'Galileo',
  'orbit': 5.2,
  'parent_planet': None,
  'period': 4383.0,
  'planet_type': 'Gas Giant',
  'radius': 11.0},
 {'description': 'Primary habitable world of Alpha Centauri A (α Cen A c) — settler name New Eden, '
                 'Directorate designation Hawking Prime. Temperate capital of the Centauran '
                 'Assembly, a Directorate client state of 700–900 million.',
  'host_star_name': 'Hawking',
  'map_url': None,
  'mass': 1.3,
  'name': 'Hawking Prime',
  'orbit': 1.1,
  'parent_planet': None,
  'period': 420.0,
  'planet_type': 'Earth-like',
  'radius': 1.05},
 {'description': 'New Switzerland: a rugged, geologically young world of folded mountains, glacial '
                 'valleys and cold high lakes — 45% land, seeded with cold-tolerant Earth and '
                 'Stahlburgher stock. Capital Nielsenstadt anchors precision manufacturing and the '
                 "rim's financial-clearing sector; its cantons answer to no Dynast, only their "
                 'ballots.',
  'host_star_name': 'Helvetia Tor',
  'map_url': None,
  'mass': None,
  'name': 'Neu Helvetica',
  'orbit': 1.7,
  'parent_planet': None,
  'period': 770.0,
  'planet_type': 'Earth-like',
  'radius': 1.0},
 {'description': 'Jupiter-like, named after the Assyrian god of war and empire. Orbital platforms '
                 'serve as trade gateways, multiple icy moons (~0.01 Earth masses) for resource '
                 'extraction (volatiles). Minimal eclipse impact (~30–50 minutes every ~8.1 '
                 'years).',
  'host_star_name': 'Holsten Tor',
  'map_url': None,
  'mass': 0.7,
  'name': 'Ashur',
  'orbit': 5.0,
  'parent_planet': None,
  'period': 4380.0,
  'planet_type': 'Gas Giant',
  'radius': 9.0},
 {'description': 'Jungle Moon orbiting Stahlburgh, vibrant trade port with biodiverse markets. '
                 'Hothouse equatorial jungles (30–40°C), tropical/sub-tropical (20–30°C), '
                 'temperate poles (5–10°C). Thick greenhouse atmosphere (1.7 atm, CO₂/CH₄/H₂O), '
                 'tidal heating (~0.15 W/m²), moderate tilt (~25°).',
  'host_star_name': 'Holsten Tor',
  'map_url': None,
  'mass': 0.5,
  'name': 'Eisenwald',
  'orbit': 0.0004,
  'parent_planet': 'Stahlburgh',
  'period': 6.0,
  'planet_type': 'Rocky Moon',
  'radius': 0.8},
 {'description': 'Neptune-like, mined for volatiles to support trade hub.',
  'host_star_name': 'Holsten Tor',
  'map_url': None,
  'mass': 3.0,
  'name': 'Eiswelt',
  'orbit': 10.0,
  'parent_planet': None,
  'period': 11680.0,
  'planet_type': 'Ice/Rocky',
  'radius': 1.7},
 {'description': 'Hot, non-habitable world with a thin atmosphere, used as a mining outpost for '
                 'metals and resources supporting the trade hub (~3.8 solar flux). Confirmed as HD '
                 '86728 b.',
  'host_star_name': 'Holsten Tor',
  'map_url': None,
  'mass': 9.2,
  'name': 'Felskern',
  'orbit': 0.1916,
  'parent_planet': None,
  'period': 31.0,
  'planet_type': 'Hot Neptune',
  'radius': 3.0},
 {'description': 'Saturn-like, named after the Assyrian god of agriculture and war. Supports '
                 'rimward trade logistics with resource-rich icy moons (3–5, ~0.01–0.1 Earth '
                 'masses) hosting fuel/trade stations.',
  'host_star_name': 'Holsten Tor',
  'map_url': None,
  'mass': 1.5,
  'name': 'Ninurta',
  'orbit': 1.2,
  'parent_planet': None,
  'period': 511.0,
  'planet_type': 'Gas Giant',
  'radius': 11.0},
 {'description': 'Alpine Prime, Felgenland Union capital with Pangaea-like supercontinent (~120 '
                 'million km²), alpine/temperate biomes (mean 10–11°C), coniferous forests, grassy '
                 'highlands. Low axial tilt (10°) for stable seasons. Hosts rugged colonies, '
                 'mining, administrative centers.',
  'host_star_name': 'Holsten Tor',
  'map_url': '/static/planet-maps/stahlburgh.html',
  'mass': 1.4,
  'name': 'Stahlburgh',
  'orbit': 1.4,
  'parent_planet': None,
  'period': 657.0,
  'planet_type': 'Rocky',
  'radius': 1.0},
 {'description': 'Outermost world of L 98-59 (L 98-59 f). Site of the destruction of ISN Bismarck '
                 'and T. Roosevelt during Terran frontier operations.',
  'host_star_name': 'L 98-59',
  'map_url': None,
  'mass': 1.4,
  'name': 'Foxtrot',
  'orbit': 0.136,
  'parent_planet': None,
  'period': 23.2,
  'planet_type': 'Rocky',
  'radius': 0.93},
 {'description': 'Frozen prison world and interrogation center of the Directorate.',
  'host_star_name': 'L 98-59',
  'map_url': None,
  'mass': 1.8,
  'name': 'Frostspire',
  'orbit': 0.22,
  'parent_planet': None,
  'period': 78.9,
  'planet_type': 'Ice Giant',
  'radius': 1.3},
 {'description': "Volcanic forge world — the Directorate's major source of rare metals; 20–30 "
                 'million.',
  'host_star_name': 'L 98-59',
  'map_url': None,
  'mass': 2.22,
  'name': 'Ironhold',
  'orbit': 0.0304,
  'parent_planet': None,
  'period': 3.69,
  'planet_type': 'Super-Earth',
  'radius': 1.385},
 {'description': 'Scorched, airless sensor-array world fortified to watch the Felgenland Union.',
  'host_star_name': 'L 98-59',
  'map_url': None,
  'mass': 0.4,
  'name': 'Outpost Scorch',
  'orbit': 0.02191,
  'parent_planet': None,
  'period': 2.25,
  'planet_type': 'Hot Rocky',
  'radius': 0.85},
 {'description': 'Turbulent gas dwarf serving as a refueling depot; 10–15 million on orbital '
                 'platforms.',
  'host_star_name': 'L 98-59',
  'map_url': None,
  'mass': None,
  'name': 'Stormhold',
  'orbit': 0.15,
  'parent_planet': None,
  'period': 45.2,
  'planet_type': 'Gas Giant',
  'radius': 3.5},
 {'description': 'Ocean world hosting floating naval fortresses; 15–20 million.',
  'host_star_name': 'L 98-59',
  'map_url': None,
  'mass': 2.31,
  'name': 'Tidal Bastion',
  'orbit': 0.045,
  'parent_planet': None,
  'period': 7.5,
  'planet_type': 'Water-rich',
  'radius': 1.57},
 {'description': 'Hellish pressure-cooker used for experimental weapons testing.',
  'host_star_name': 'L 98-59',
  'map_url': None,
  'mass': 3.0,
  'name': "Viper's Cauldron",
  'orbit': 0.06,
  'parent_planet': None,
  'period': 12.8,
  'planet_type': 'Super-Venus',
  'radius': None},
 {'description': 'Neptune-like giant (Lalande 21185 c) whose icy moons are worked for volatiles; '
                 'orbital platforms serve as refueling stations for 10–20 million.',
  'host_star_name': 'Lalande 21185',
  'map_url': None,
  'mass': 13.6,
  'name': 'Gaso',
  'orbit': 2.94,
  'parent_planet': None,
  'period': 2946.0,
  'planet_type': 'Gas Giant',
  'radius': 4.0},
 {'description': 'First human colony established outside the Sol system (Lalande 21185 b). Now a '
                 'contested world in the border wars.',
  'host_star_name': 'Lalande 21185',
  'map_url': None,
  'mass': 1.0,
  'name': 'Libertad',
  'orbit': 0.16,
  'parent_planet': None,
  'period': 37.0,
  'planet_type': 'Rocky',
  'radius': 0.8},
 {'description': 'Serene aurora-lit world (Lalande 21185 e) of archipelagos and boreal forests — '
                 "the system's cultural hub post-2357; 30–50 million.",
  'host_star_name': 'Lalande 21185',
  'map_url': None,
  'mass': 1.5,
  'name': 'Lumirima',
  'orbit': 0.2,
  'parent_planet': None,
  'period': 80.0,
  'planet_type': 'Earth-like',
  'radius': 1.0},
 {'description': 'Storm-swept ocean world (Lalande 21185 g), 80% sea with island continents — '
                 'maritime trade ports vital post-2357; 20–30 million.',
  'host_star_name': 'Lalande 21185',
  'map_url': None,
  'mass': 1.8,
  'name': 'Marhavo',
  'orbit': 0.3,
  'parent_planet': None,
  'period': 150.0,
  'planet_type': 'Earth-like',
  'radius': 1.0},
 {'description': "Lalande 21185 c — bitter contested war zone. Site of Max's long patrol campaign.",
  'host_star_name': 'Lalande 21185',
  'map_url': None,
  'mass': 1.3,
  'name': 'Nakdong',
  'orbit': 0.13,
  'parent_planet': None,
  'period': 27.0,
  'planet_type': 'Rocky',
  'radius': 0.85},
 {'description': 'Warm savanna-and-desert world (Lalande 21185 f) of agricultural colonies, a '
                 'trade outpost post-2357; 50–70 million.',
  'host_star_name': 'Lalande 21185',
  'map_url': None,
  'mass': 2.0,
  'name': 'Verdkampo',
  'orbit': 0.25,
  'parent_planet': None,
  'period': 110.0,
  'planet_type': 'Earth-like',
  'radius': 1.1},
 {'description': 'Warm-temperate capital of the Pentothian Trade Conglomerate — Auricore City and '
                 'its orbital trade stations.',
  'host_star_name': 'Pentothia Prime',
  'map_url': None,
  'mass': 1.5,
  'name': 'Auricore',
  'orbit': 0.4,
  'parent_planet': None,
  'period': 113.0,
  'planet_type': 'Super-Earth',
  'radius': 1.2},
 {'description': "The Pentothian answer to Protelan's jump geometry: a great cycler shuttling the "
                 'long crawl between the Stellarion Trade Nexus and Auricore, lined like a '
                 'medieval bridge with shops and mercantile bazaars — spend money while you wait '
                 'to arrive.',
  'host_star_name': 'Pentothia Prime',
  'map_url': None,
  'mass': None,
  'name': 'Auricore Cycler',
  'orbit': 95.0,
  'parent_planet': None,
  'period': None,
  'planet_type': 'Cycler',
  'radius': None},
 {'description': 'Frozen world mined for fusion-grade isotopes.',
  'host_star_name': 'Pentothia Prime',
  'map_url': None,
  'mass': 2.0,
  'name': 'Cryon',
  'orbit': 1.0,
  'parent_planet': None,
  'period': 446.0,
  'planet_type': 'Ice Giant',
  'radius': 1.3},
 {'description': 'Resource-rich belt mined for iridium and osmium.',
  'host_star_name': 'Pentothia Prime',
  'map_url': None,
  'mass': None,
  'name': 'Ferrum Belt',
  'orbit': 0.3,
  'parent_planet': None,
  'period': 45.0,
  'planet_type': 'Asteroid Belt',
  'radius': None},
 {'description': 'A ~100 km orbital station in the far dark — sternfomotor docks and the '
                 "Conglomerate's great trade markets, parked out beyond the star's jump radius "
                 'where the ships arrive.',
  'host_star_name': 'Pentothia Prime',
  'map_url': None,
  'mass': None,
  'name': 'Stellarion Trade Nexus',
  'orbit': 189.98,
  'parent_planet': None,
  'period': 547900.0,
  'planet_type': 'Station',
  'radius': None},
 {'description': 'Scorched, mineral-rich Pentothian mining outpost.',
  'host_star_name': 'Pentothia Prime',
  'map_url': None,
  'mass': 0.8,
  'name': 'Vulcara',
  'orbit': 0.05,
  'parent_planet': None,
  'period': 4.5,
  'planet_type': 'Hot Rocky',
  'radius': 0.9},
 {'description': 'Hot, Venus-like mining outpost for metals.',
  'host_star_name': 'Protelan',
  'map_url': None,
  'mass': 1.5,
  'name': 'Chaud',
  'orbit': 0.3,
  'parent_planet': None,
  'period': 33.0,
  'planet_type': 'Hot Rocky',
  'radius': 1.2},
 {'description': 'Cool, Mars-like world worked for rare earths.',
  'host_star_name': 'Protelan',
  'map_url': None,
  'mass': 0.5,
  'name': 'Frais',
  'orbit': 1.0,
  'parent_planet': None,
  'period': 347.0,
  'planet_type': 'Rocky',
  'radius': 0.8},
 {'description': 'Cold, barren outer world.',
  'host_star_name': 'Protelan',
  'map_url': None,
  'mass': 0.5,
  'name': 'Froid',
  'orbit': 4.0,
  'parent_planet': None,
  'period': 2191.0,
  'planet_type': 'Rocky',
  'radius': 0.8},
 {'description': 'The vast, grandfatherly Neptune-like giant (French grand-père) at 154 AU — '
                 'beyond the ~56 AU sternfomotor jump periphery, so ships jump directly to its '
                 'orbit, a prized shortcut to the Protelani capital. It fills the sky of its '
                 'capital moon Protelan, its reflective phases driving the Starveil Festival. That '
                 'jump geometry made the moon rich.',
  'host_star_name': 'Protelan',
  'map_url': None,
  'mass': 120.0,
  'name': 'Grandpere',
  'orbit': 154.0,
  'parent_planet': None,
  'period': 706000.0,
  'planet_type': 'Gas Giant',
  'radius': 8.5},
 {'description': 'Distant desert world mined for volatiles.',
  'host_star_name': 'Protelan',
  'map_url': None,
  'mass': 0.3,
  'name': 'Hiver',
  'orbit': 73.0,
  'parent_planet': None,
  'period': 182620.0,
  'planet_type': 'Rocky',
  'radius': 0.7},
 {'description': 'Jupiter-like inner giant (Joi, "joy") at 2.5 AU — its icy moons anchor part of '
                 "the Protelani system's mining and logistics.",
  'host_star_name': 'Protelan',
  'map_url': None,
  'mass': None,
  'name': 'Joi',
  'orbit': 2.5,
  'parent_planet': None,
  'period': 1096.0,
  'planet_type': 'Gas Giant',
  'radius': 12.0},
 {'description': 'Capital moon of the Protelan Republic, orbiting the gas giant Grandpere at 154 '
                 'AU — beyond the jump periphery, so ships jump straight in and out, which made it '
                 "the Rim's mercantile crossroads and the Republic rich. A sunless world so far "
                 'from its star: kept temperate (15–25°C) purely by tidal heating from Grandpere, '
                 'under a thick greenhouse atmosphere. Its low-light ecology is exotic — fungal, '
                 'mushroom-forest and bioluminescent rather than sun-driven. Seat of the '
                 'ultra-capitalist government at Havskrun.',
  'host_star_name': 'Protelan',
  'map_url': None,
  'mass': 0.85,
  'name': 'Protelan',
  'orbit': 0.0011,
  'parent_planet': 'Grandpere',
  'period': 12.5,
  'planet_type': 'Rocky Moon',
  'radius': 0.72},
 {'description': 'Flare-battered habitable-zone world; its orbital station shelters 2–4 million.',
  'host_star_name': 'Proxima Centauri',
  'map_url': None,
  'mass': 1.07,
  'name': 'Hubble Outpost',
  'orbit': 0.0485,
  'parent_planet': None,
  'period': 11.2,
  'planet_type': 'Rocky',
  'radius': 1.1},
 {'description': 'Habitable blue planet with oceans, continents, diverse life, and Terran '
                 'Directorate homeworld—fractured post-2035 Attack.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 1.0,
  'name': 'Earth',
  'orbit': 1.0,
  'parent_planet': None,
  'period': 365.0,
  'planet_type': 'Terrestrial',
  'radius': 1.0},
 {'description': 'Largest planet with Great Red Spot storm, 95+ moons, strong magnetic field.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 317.8,
  'name': 'Jupiter',
  'orbit': 5.2,
  'parent_planet': None,
  'period': 4333.0,
  'planet_type': 'Gas Giant',
  'radius': 11.21},
 {'description': 'Red desert world with polar ice caps, ancient volcanoes, and potential for human '
                 'colonies.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 0.107,
  'name': 'Mars',
  'orbit': 1.52,
  'parent_planet': None,
  'period': 687.0,
  'planet_type': 'Terrestrial',
  'radius': 0.532},
 {'description': 'Innermost rocky planet with extreme temperatures, no atmosphere, heavily '
                 'cratered.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 0.055,
  'name': 'Mercury',
  'orbit': 0.39,
  'parent_planet': None,
  'period': 88.0,
  'planet_type': 'Terrestrial',
  'radius': 0.383},
 {'description': 'Windy blue world with Great Dark Spot, 14 moons, Triton retrograde moon.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 17.15,
  'name': 'Neptune',
  'orbit': 30.1,
  'parent_planet': None,
  'period': 60190.0,
  'planet_type': 'Ice Giant',
  'radius': 3.88},
 {'description': 'Ringed beauty with 146 moons, hexagonal storm at north pole.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 95.16,
  'name': 'Saturn',
  'orbit': 9.58,
  'parent_planet': None,
  'period': 10759.0,
  'planet_type': 'Gas Giant',
  'radius': 9.45},
 {'description': "Saturn's colonized moon — birthplace of Lena Kocher, mother of the Phoenix "
                 'Exodus.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 0.0225,
  'name': 'Titan',
  'orbit': 9.58,
  'parent_planet': 'Saturn',
  'period': None,
  'planet_type': 'Rocky Moon',
  'radius': 0.2495},
 {'description': 'Tilted sideways with faint rings, 27 moons, extreme seasons.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 14.54,
  'name': 'Uranus',
  'orbit': 19.2,
  'parent_planet': None,
  'period': 30687.0,
  'planet_type': 'Ice Giant',
  'radius': 4.01},
 {'description': 'Hot greenhouse world with thick CO2 atmosphere, volcanic surface, retrograde '
                 'rotation.',
  'host_star_name': 'Sol',
  'map_url': None,
  'mass': 0.815,
  'name': 'Venus',
  'orbit': 0.72,
  'parent_planet': None,
  'period': 225.0,
  'planet_type': 'Terrestrial',
  'radius': 0.949},
 {'description': 'Primary habitable colony world of the Tau Ceti system. Under Terran Directorate '
                 'administration. Named for Isaac Asimov.',
  'host_star_name': 'Tau Ceti',
  'map_url': None,
  'mass': 2.0,
  'name': 'Asimov',
  'orbit': 0.552,
  'parent_planet': None,
  'period': 168.12,
  'planet_type': 'Earth-like',
  'radius': 1.05},
 {'description': 'Cratered, airless moon of Asimov — Tau Ceti e I — ringed with orbital defense '
                 'platforms; 10–15 million live in its warrens. Site of the December 2355 battle '
                 'where General Musa defected. Named for Alfred Bester.',
  'host_star_name': 'Tau Ceti',
  'map_url': None,
  'mass': 0.01,
  'name': 'Bester',
  'orbit': 0.002,
  'parent_planet': 'Asimov',
  'period': 2.5,
  'planet_type': 'Rocky Moon',
  'radius': None},
 {'description': 'Hot, rocky world of Directorate weapons-testing bunkers; 80–100 million.',
  'host_star_name': 'Tau Ceti',
  'map_url': None,
  'mass': 3.1,
  'name': 'Bradbury',
  'orbit': 0.133,
  'parent_planet': None,
  'period': 20.0,
  'planet_type': 'Super-Earth',
  'radius': None},
 {'description': 'Dense, iron-rich world under a thin CO₂ atmosphere; 50–70 million.',
  'host_star_name': 'Tau Ceti',
  'map_url': None,
  'mass': 3.6,
  'name': 'Clarke',
  'orbit': 0.195,
  'parent_planet': None,
  'period': 34.7,
  'planet_type': 'Super-Earth',
  'radius': None},
 {'description': 'Sweltering jungle world — Tau Ceti b — a chaotic frontier of 100–120 million.',
  'host_star_name': 'Tau Ceti',
  'map_url': None,
  'mass': 2.0,
  'name': 'Heinlein',
  'orbit': 0.105,
  'parent_planet': None,
  'period': 13.665,
  'planet_type': 'Super-Earth',
  'radius': 1.1},
 {'description': 'Cold world on the outer habitable edge — icy continents, 70–90 million.',
  'host_star_name': 'Tau Ceti',
  'map_url': None,
  'mass': 3.9,
  'name': 'Herbert',
  'orbit': 1.334,
  'parent_planet': None,
  'period': 636.13,
  'planet_type': 'Super-Earth',
  'radius': None},
 {'description': "Cold rocky world just beyond Herbert — Tau Ceti g — past the habitable zone's "
                 'outer edge, its modest population sheltered in domed and valley settlements. A '
                 'quiet frontier that saw little of the war; post-2361, a Cetan Confederacy '
                 'enclave. Named for Poul Anderson.',
  'host_star_name': 'Tau Ceti',
  'map_url': None,
  'mass': 1.5,
  'name': 'Poul',
  'orbit': 1.7,
  'parent_planet': None,
  'period': 915.0,
  'planet_type': 'Rocky',
  'radius': 0.9},
 {'description': 'HD 86729 c — Union frontier colony transitioning from outpost to full colonial '
                 'world. The "gateway to the deep frontier."',
  'host_star_name': 'Tiefe-Grenze Tor',
  'map_url': None,
  'mass': 1.2,
  'name': 'Brandstadt',
  'orbit': 0.8,
  'parent_planet': None,
  'period': 280.0,
  'planet_type': 'Earth-like',
  'radius': 0.9},
 {'description': 'Hot, Venus-like world mined for rare metals.',
  'host_star_name': 'Tiefe-Grenze Tor',
  'map_url': None,
  'mass': 0.6,
  'name': 'Felsbrand',
  'orbit': 0.4,
  'parent_planet': None,
  'period': 55.0,
  'planet_type': 'Hot Rocky',
  'radius': 0.9},
 {'description': 'Neptune-like iceworld of methane and water ices.',
  'host_star_name': 'Tiefe-Grenze Tor',
  'map_url': None,
  'mass': 2.0,
  'name': 'Frostkern',
  'orbit': 8.0,
  'parent_planet': None,
  'period': 8401.0,
  'planet_type': 'Ice Giant',
  'radius': 1.5},
 {'description': 'Jupiter-like giant whose moons supply volatiles.',
  'host_star_name': 'Tiefe-Grenze Tor',
  'map_url': None,
  'mass': None,
  'name': 'Sturmholz',
  'orbit': 2.5,
  'parent_planet': None,
  'period': 1461.0,
  'planet_type': 'Gas Giant',
  'radius': 10.0},
 {'description': 'Arid world orbiting Toliman, used for military training; 3–5 million residents.',
  'host_star_name': 'Toliman',
  'map_url': None,
  'mass': 0.8,
  'name': 'Kepler',
  'orbit': 0.7,
  'parent_planet': None,
  'period': 219.0,
  'planet_type': 'Rocky',
  'radius': 0.9}]


def main():
    con = sqlite3.connect(DB_PATH)
    try:
        for sql in CLEANUP_SQL:
            con.execute(sql)

        placeholders = ",".join("?" * len(FULL_STAR_COLUMNS))
        collist = ",".join(FULL_STAR_COLUMNS)
        for row in FULL_STARS:
            con.execute(
                f"INSERT OR REPLACE INTO stars ({collist}) VALUES ({placeholders})",
                [row[c] for c in FULL_STAR_COLUMNS])
        for s in STARS:
            con.execute(
                "UPDATE stars SET fictional_name=?, fictional_description=?, nation_id=?, "
                "discovery_number=?, discovery_year=?, era_start=?, era_end=? WHERE id=?",
                (s["fictional_name"], s["fictional_description"], s["nation_id"],
                 s["discovery_number"], s["discovery_year"], s["era_start"], s["era_end"], s["id"]))
        for n in NATIONS:
            con.execute("UPDATE nations SET era_start=?, era_end=? WHERE id=?",
                        (n["era_start"], n["era_end"], n["id"]))
        for r in TRADE_ROUTES:
            con.execute("UPDATE trade_routes SET era_start=?, era_end=? WHERE id=?",
                        (r["era_start"], r["era_end"], r["id"]))
        for p in EXOPLANET_FICTIONAL_FLAGS:
            cur = con.execute(
                "UPDATE exoplanets SET is_fictional=1, semi_major_axis_au=?, orbital_period_days=?, "
                "planet_radius_earth=?, planet_mass_earth=?, equilibrium_temp_k=?, planet_type=?, "
                "potentially_habitable=?, star_id=? WHERE name=? AND host_star_name=?",
                (p["semi_major_axis_au"], p["orbital_period_days"], p["planet_radius_earth"],
                 p["planet_mass_earth"], p["equilibrium_temp_k"], p["planet_type"],
                 p["potentially_habitable"], p["star_id"], p["name"], p["host_star_name"]))
            if cur.rowcount == 0:
                con.execute(
                    "INSERT INTO exoplanets (name, host_star_name, is_fictional, semi_major_axis_au, "
                    "orbital_period_days, planet_radius_earth, planet_mass_earth, equilibrium_temp_k, "
                    "planet_type, potentially_habitable, star_id) VALUES (?,?,1,?,?,?,?,?,?,?,?)",
                    (p["name"], p["host_star_name"], p["semi_major_axis_au"], p["orbital_period_days"],
                     p["planet_radius_earth"], p["planet_mass_earth"], p["equilibrium_temp_k"],
                     p["planet_type"], p["potentially_habitable"], p["star_id"]))

        # Authoritative fictional worlds table
        con.execute("DELETE FROM fictional_exoplanets")
        fcols = ",".join(FICTIONAL_WORLD_COLUMNS)
        fph = ",".join("?" * len(FICTIONAL_WORLD_COLUMNS))
        for w in FICTIONAL_WORLDS:
            con.execute(f"INSERT INTO fictional_exoplanets ({fcols}) VALUES ({fph})",
                        [w[c] for c in FICTIONAL_WORLD_COLUMNS])

        con.commit()
        print(f"star canon: {len(FULL_STARS)} full stars, {len(STARS)} star updates, "
              f"{len(NATIONS)} nations, {len(TRADE_ROUTES)} routes, "
              f"{len(EXOPLANET_FICTIONAL_FLAGS)} exo flags, "
              f"{len(FICTIONAL_WORLDS)} fictional worlds (authoritative)")
    finally:
        con.close()


if __name__ == "__main__":
    main()
